(include_subdirs unqualified)
(env
 (_
  (flags
   (:standard -w +4+9-30+44+45+48-69-70))))

(library
 (name mlir)
 (wrapped false)
 (flags
  (:standard
   -open
   Mlir_frontend
   -open
   Mlir_lowering
   -open
   Mlir_dialect))
 (ocamlopt_flags
  (:standard
   (:include %{project_root}/ocamlopt_flags.sexp)
   -O3))
 (modules_without_implementation direct frontend through_mlir types)
 (libraries
  ocamlcommon
  ocamlbytecomp
  ocamloptcomp
  mlir_dialect
  mlir_lowering
  mlir_frontend))
